# Generated by Django 3.0.5 on 2020-05-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr1', models.CharField(max_length=120)),
                ('addr2', models.CharField(blank=True, max_length=120, null=True)),
                ('addr3', models.CharField(blank=True, max_length=120, null=True)),
                ('addr4', models.CharField(blank=True, max_length=120, null=True)),
                ('town', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_text', models.TextField(blank=True, default='')),
                ('author', models.CharField(max_length=120)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Medical Histories',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contractor_code', models.CharField(default='', max_length=10, null=True)),
                ('owner', models.CharField(default='', max_length=120, null=True)),
                ('address1', models.CharField(default='', max_length=120, null=True)),
                ('address2', models.CharField(default='', max_length=120, null=True)),
                ('address3', models.CharField(default='', max_length=120, null=True)),
                ('address4', models.CharField(default='', max_length=120, null=True)),
                ('town', models.CharField(default='', max_length=40, null=True)),
                ('pcde', models.CharField(default='', max_length=10, null=True)),
                ('tel', models.CharField(default='', max_length=20, null=True)),
                ('fax', models.CharField(default='', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'ordering': ('town', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('accepts_sms', models.NullBooleanField()),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('chi', models.CharField(blank=True, max_length=10, null=True)),
                ('alt_ref', models.CharField(blank=True, max_length=40, null=True)),
                ('dentist', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('addresses', models.ManyToManyField(blank=True, to='covid.Address')),
                ('emails', models.ManyToManyField(blank=True, to='covid.Email')),
                ('telephones', models.ManyToManyField(blank=True, to='covid.Telephone')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.Record')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40, null=True)),
                ('surname', models.CharField(max_length=40)),
                ('is_default', models.BooleanField(default=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.Record')),
            ],
            options={
                'ordering': ('surname', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(0, 'Other Conditions'), (1, 'Warnings'), (2, 'Habits'), (3, 'Heart'), (4, 'Chest'), (5, 'Blood'), (6, 'Allergies')], default=0)),
                ('note', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('medhist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.MedicalHistory')),
            ],
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.Record'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=240)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.Record')),
            ],
            options={
                'ordering': ('record', 'is_urgent', 'is_completed', '-date_edited'),
            },
        ),
    ]
